### ISSUE TITLE
Feature Request : uMQTT Broker

### ISSUE THREAD

**Issue by happytm** [philbowles/h4plugins#1]
Wow. I must tell you this is very extensive library. It will be  almost swiss army knife for ESP devices as standalone local sensor network once MYSQL logger & possibly  web server displaying all data collected by logger code like your esparto is implemented. Also thank you for your extensive documentation which is absolutely necessary for good framework.

I am requesting implementation of excellent uMQTT broker if possible. I amusing uMQTT broker for my standalone sensor network for some time and it is very reliable. Basically it is very robust local broker on network. It does not require internet for local only communication. Following are links:

https://github.com/martin-ger/uMQTTBroker
https://www.youtube.com/watch?v=0K9q4IuB_oA&t=10s

My implementation of uMQTT broker is linked below:

https://github.com/happytm/BatteryNode

Please keep it up.
Thank you.

**Comment by philbowles** [comment]
Thanks for the support and kind words - I use mosquttio on a Raspberry Pi - in my opinion small MCU are not suitable for serious MQTT server. 

O have no plans to add an MQTT broker to H4 - and don't hold your breath, because it is not something I will ever do. :)
