### ISSUE TITLE
Missing header file in <config_plugins.h>

### ISSUE THREAD

**Issue by noschang** [philbowles/h4plugins#19]
When trying to run the [tone example](https://github.com/philbowles/h4plugins/blob/master/examples/MUSIC/H4P_TakeOnMe/H4P_TakeOnMe.ino) in PlatoformIO, the compiler produces the following errors:

```
In file included from .pio/libdeps/esp32dev/H4Plugins/src/H4Plugins.h:3:0,
                 from src/main.cpp:3:
.pio/libdeps/esp32dev/H4Plugins/src/config_plugins.h:72:6: error: use of enum 'H4PM_SENSE' without previous declaration
 enum H4PM_SENSE:uint8_t {
      ^
.pio/libdeps/esp32dev/H4Plugins/src/config_plugins.h:72:16: error: expected unqualified-id before ':' token
 enum H4PM_SENSE:uint8_t {
                ^
In file included from .pio/libdeps/esp32dev/H4Plugins/src/H4P_Signaller.h:33:0,
                 from .pio/libdeps/esp32dev/H4Plugins/src/H4P_AsyncMQTT.h:33,
                 from .pio/libdeps/esp32dev/H4Plugins/src/H4Plugins.h:10,
```

After some investigation, I've found out that the issue is that ```uint8_t``` is not recognized in this context/scope, causing the enum declaration to fail.

It turns out that, when using Arduino IDE, the file ```<Arduino.h>``` is automatically included by the framework, even if not included explicitly by the user in the top of the ```main.cpp``` file. The header ```<Arduino.h>``` includes the ```<stdint.h>``` which contains the definition for ```uint8_t```.

Including ```<stdint.h>``` on top of the ```<config_plugins.h``` file fixes the problem and makes the example compile. In fact, this header could be included on all files that make use of the ```std``` library types like ```uint8_t```, ```uint16_t```, ```uint32_t```, etc..., in order to prevent future compiling errors.

**Comment by philbowles** [comment]
Once again, this is a PlatformIO problem. ArduinoIDE insert the Arduino.h file for all builds. Thanks for your efforts, other PIO users may find this helpful. My policy of 100% ArduinoIDE compatibility means that I will not be making any changes :(
