### ISSUE TITLE
error: 'TAG' was not declared in this scope (H4P_Timekeeper.cpp)

### ISSUE THREAD

**Issue by kebasaa** [philbowles/h4plugins#4]
Hi,

Sorry to open a new issue, I didn't know how to re-open the other one. The issue of timekeeping is still there. I can see in the code that there is a call to TAG, but it isn't declared anywhere I could find... How can this be solved? Thanks

```
...\Documents\Arduino\libraries\h4plugins-0.5.5\src\H4P_Timekeeper.cpp: In member function 'uint32_t H4P_Timekeeper::__alarmCore(std::vector<std::basic_string<char> >, bool, H4BS_FN_SWITCH)':

...\Documents\Arduino\libraries\h4plugins-0.5.5\src\H4P_Timekeeper.cpp:104:71: error: 'TAG' was not declared in this scope

         },msDue,daily ? msDue:0,H4Countdown(1),nullptr,TAG(daily ? 7:3));

                                                                       ^

exit status 1
Error compiling for board Generic ESP8266 Module.
```

**Comment by kebasaa** [comment]
I'm sorry to write through here, as I don't have facebook. The issue is a weird one, and I can see that TAG is declared in the H4 library, but somehow on my setup, it doesn't even compile.

I've tried with multiple different board definitions, but my board is the Lolin/Wemos D1 mini. I don't know if that helps. All additional libraries were installed as instructed, and the Arduino IDE is 1.8.12

**Comment by philbowles** [comment]
What version of H4 are you using?

**Comment by kebasaa** [comment]
I'm using 0.5.4

**Comment by kebasaa** [comment]
Thanks for pointing it out. It appears that cloning the master repository of H4 works, but not the 0.5.4 release. There must be a tiny difference between the two

**Comment by philbowles** [comment]
@kebasaa 1) you should not clone the release, just download the zip library. You should *always* download the latest master

**Comment by kebasaa** [comment]
Thanks a lot for your help. My mistake, I meant I downloaded the zip of the release, I didn't clone it. I'm now working with the zip of the master. Should I also always download the latest master of h4plugins, or rather the release?
